
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: car_rental_back_end_development
test:
  <<: *default
  database: car_rental_back_end_test
production:
  <<: *default
  database: car_rental_back_end_production
  username: car_rental_back_end
  password: <%= ENV["CAR_RENTAL_BACK_END_DATABASE_PASSWORD"] %>
